# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Birthday',
            field=models.DateField(null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Education',
            field=models.CharField(max_length=25, null=True, verbose_name='教育经历'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Familiar',
            field=models.CharField(max_length=25, null=True, verbose_name='熟悉领域'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Job',
            field=models.CharField(max_length=25, null=True, verbose_name='工作'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Nickname',
            field=models.CharField(max_length=8, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6),
        ),
    ]
