# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180102_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Sex',
            field=models.CharField(choices=[('男', 'male'), ('女', 'female')], default='男', max_length=6),
        ),
    ]
