# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180102_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Birthday',
            field=models.DateField(default='1111-11-11', null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Education',
            field=models.CharField(default='', max_length=25, null=True, verbose_name='教育经历'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Familiar',
            field=models.CharField(default='', max_length=25, null=True, verbose_name='熟悉领域'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Job',
            field=models.CharField(default='', max_length=25, null=True, verbose_name='工作'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Nickname',
            field=models.CharField(default='', max_length=8, null=True, verbose_name='昵称'),
        ),
    ]
