# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 16:35
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_Time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('Modify_Time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('Click_Num', models.IntegerField(default=0, verbose_name='点击量')),
                ('Tittle', models.CharField(max_length=20, null=True, verbose_name='标题')),
                ('Cover_img', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='封面图片')),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='内容')),
                ('Label', models.CharField(max_length=10, null=True, verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_Time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('Category', models.CharField(max_length=15, verbose_name='分类')),
                ('Article_Num', models.IntegerField(default=0, verbose_name='文章数')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_Time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('Content', models.CharField(max_length=100, verbose_name='评论内容')),
                ('Comment_ComId', models.IntegerField(default=0, verbose_name='被评论用户')),
                ('Like_Num', models.IntegerField(default=0, verbose_name='点赞量')),
                ('IP', models.CharField(max_length=15, null=True, verbose_name='Ip地址')),
                ('Comment_Address', models.CharField(max_length=10, null=True, verbose_name='地址')),
                ('Comment_Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Article_id', to='article.Article')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='RecommendArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_Time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('Recommend_Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='推荐文章')),
            ],
            options={
                'verbose_name': '推荐文章',
                'verbose_name_plural': '推荐文章',
            },
        ),
    ]
