# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 14:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_Time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('Modify_Time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('Click_Num', models.IntegerField(default=0, verbose_name='点击量')),
                ('Tittle', models.CharField(max_length=20, null=True, verbose_name='标题')),
                ('Cover_img', models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='封面图片')),
                ('Content', models.CharField(max_length=1000, verbose_name='内容')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_Time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('Content', models.CharField(max_length=100, verbose_name='评论内容')),
                ('Comment_Article', models.IntegerField(verbose_name='评论文章')),
                ('Comment_ComId', models.IntegerField(default=0, verbose_name='评论用户')),
                ('Like_Num', models.IntegerField(default=0, verbose_name='点赞量')),
                ('IP', models.CharField(max_length=15, verbose_name='Ip地址')),
                ('Comment_Address', models.CharField(max_length=10, verbose_name='地址')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
