# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comment_Address',
            field=models.CharField(max_length=10, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Comment_Article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Article_id', to='article.Article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='IP',
            field=models.CharField(max_length=15, null=True, verbose_name='Ip地址'),
        ),
    ]
