# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171211_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_Time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Category', models.CharField(max_length=15, verbose_name='分类')),
                ('Article_Num', models.IntegerField(default=0, verbose_name='文章数')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='Article_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Article_Category', to='article.Category'),
        ),
    ]
