# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 14:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20171221_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='内容'),
        ),
    ]
