# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20180106_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Create_Time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
