# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180106_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Label',
            field=models.CharField(max_length=10, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Article_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Article_Category', to='article.Category', verbose_name='文章分类'),
        ),
    ]
