# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20180108_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_Time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('Recommend_Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='推荐文章')),
            ],
            options={
                'verbose_name': '推荐文章',
                'verbose_name_plural': '推荐文章',
            },
        ),
    ]
